# Generated by Django 4.2 on 2023-10-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_coef', models.FloatField(default=0.5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('end_reg', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/images')),
                ('adress', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('categories', models.ManyToManyField(to='recommendations.category')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.organizerprofile', to_field='organization')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.events')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.participantprofile')),
            ],
        ),
    ]
