# Generated by Django 4.2 on 2023-10-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organizerprofile_participantprofile_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.organizerprofile', to_field='organization'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_coef', models.FloatField(default=0.5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.events')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.participantprofile')),
            ],
        ),
    ]
