# Generated by Django 4.2 on 2023-10-21 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_organizerprofile_participantprofile_and_more'),
        ('recommendations', '0002_events_organizer_userpreferences_eventregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='recommendations.UserPreferences', to='recommendations.category'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='events',
            field=models.ManyToManyField(through='recommendations.EventRegister', to='recommendations.events'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
